const DURATION=30*60, M1=10*60, M2=20*60;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={timer:null};
function load(){return JSON.parse(localStorage.getItem('puppyDinner')||'{"history":{},"goal":500,"active":null}')}
function save(d){localStorage.setItem('puppyDinner',JSON.stringify(d))}
function dateKey(d=new Date()){return d.toLocaleDateString('en-CA')}
function weekStart(d=new Date()){let x=new Date(d);let day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);return x}
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='weekScreen')renderWeek()}
$('#homeBtn').onclick=()=>showScreen('homeScreen');$('#weekBtn').onclick=()=>showScreen('weekScreen');
function startDinner(){let d=load();d.active={start:Date.now(),foodDone:false,waterDone:false,foodShown:false,waterShown:false};save(d);$('#preDinnerCard').classList.add('hidden');$('#timerCard').classList.remove('hidden');tick();state.timer=setInterval(tick,1000)}
$('#startBtn').onclick=startDinner;
function activeElapsed(a){return Math.max(0,Math.floor((Date.now()-a.start)/1000))}
function tick(){let d=load(),a=d.active;if(!a)return;let e=activeElapsed(a),left=Math.max(0,DURATION-e);$('#timer').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;$('#progressFill').style.width=Math.min(100,e/DURATION*100)+'%';let stage=e<M1?1:e<M2?2:3;$('#roundLabel').textContent=`ROUND ${stage} • ${stage===1?'DINNER TIME':stage===2?'KEEP IT GOING':'FINAL STRETCH'}`;$('#encouragement').textContent=stage===1?'Great eating! Cheeseball is cheering for you!':stage===2?'Awesome job! You made it to Round 2!':'Final stretch — show those puppy judges your best dinner manners!';if(e>=M1&&!a.foodShown){a.foodShown=true;save(d);foodGame();return}if(e>=M2&&!a.waterShown){a.waterShown=true;save(d);waterGame();return}if(e>=DURATION){clearInterval(state.timer);state.timer=null;finishScoring()}}
function modal(html){$('#modalCard').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function foodGame(){modal(`<div class="ribbon">10 MINUTE CHECK-IN</div><h2>Feed Cheeseball!</h2><p>Tap all the food to help Cheeseball clean his bowl!</p><div class="game-stage" id="foodStage"><div class="tap-hint">TAP THE KIBBLE! 👇</div><div class="bowl"></div></div><div id="foodCount"><b>8</b> bites left</div>`);let stage=$('#foodStage'),positions=[[34,142],[92,128],[150,145],[60,180],[123,175],[180,178],[86,202],[146,205]];positions.forEach((p,i)=>{let k=document.createElement('button');k.className='kibble';k.style.left=`calc(50% - 115px + ${p[0]}px)`;k.style.top=p[1]+'px';k.setAttribute('aria-label','Eat bite');k.onclick=()=>{if(k.classList.contains('eaten'))return;k.classList.add('eaten');let left=$$('.kibble:not(.eaten)').length;$('#foodCount').innerHTML=`<b>${left}</b> bites left`;if(!left)setTimeout(()=>winMini('foodDone','Bowl Clean!','Great job eating!'),350)};stage.appendChild(k)})}
function waterGame(){modal(`<div class="ribbon">20 MINUTE CHECK-IN</div><h2>Water Break!</h2><p>Tap the cup to help Cheeseball drink all the water!</p><div class="game-stage"><div class="tap-hint">TAP THE CUP 6 TIMES! 💧</div><button id="cupBtn" class="cup" aria-label="Drink water"><div class="water" id="water"></div><div class="cup-lines"><i></i><i></i><i></i><i></i></div></button></div><div id="sipCount"><b>6</b> sips left</div>`);let sips=0;$('#cupBtn').onclick=()=>{sips++;$('#water').style.height=Math.max(0,84-(sips/6*84))+'%';$('#sipCount').innerHTML=`<b>${Math.max(0,6-sips)}</b> sips left`;if(sips>=6)setTimeout(()=>winMini('waterDone','Cup Empty!','Amazing drinking!'),350)}}
function winMini(key,title,copy){let d=load();if(d.active)d.active[key]=true;save(d);confetti();modal(`<div class="mini-dog"></div><h2>${title}</h2><p>${copy} Cheeseball gives you a puppy high-five! 🐾</p><button class="action-btn" id="continueBtn">BACK TO DINNER</button>`);$('#continueBtn').onclick=()=>{closeModal();tick()}}
function finishScoring(){let toggles=[['food','🍽️','Ate a lot of food'],['water','💧','Drank a lot of water'],['feet','🦶','Kept feet off the table'],['chair','🪑','Kept the chair on the floor']];modal(`<div class="ribbon">FINAL JUDGING</div><h2>How Did Dinner Go?</h2><p>Tap everything your little champion did tonight.</p><div class="score-grid">${toggles.map(x=>`<button class="score-toggle" data-key="${x[0]}"><span class="check">✓</span><span>${x[1]} ${x[2]}</span></button>`).join('')}</div><div class="score-total"><span id="liveScore">0</span><small>/100</small></div><button class="action-btn" id="saveScore">AWARD RIBBON 🏆</button>`);$$('.score-toggle').forEach(b=>b.onclick=()=>{b.classList.toggle('on');$('#liveScore').textContent=$$('.score-toggle.on').length*25});$('#saveScore').onclick=saveScore}
function saveScore(){let score=$$('.score-toggle.on').length*25,d=load(),k=dateKey();d.history[k]={score,items:Object.fromEntries($$('.score-toggle').map(b=>[b.dataset.key,b.classList.contains('on')])),at:Date.now()};d.active=null;save(d);confetti();$('#puppy').classList.add('celebrate');modal(`<div class="mini-dog"></div><div class="ribbon">DINNER COMPLETE</div><h2>${score>=100?'Blue Ribbon Dinner!':score>=75?'Gold Paw Dinner!':score>=50?'Great Puppy Show!':'Good Try, Pup!'}</h2><div class="score-total">${score}<small>/100</small></div><p>${score>=75?'The crowd is cheering!':'Every dinner is another chance to earn ribbons.'}</p><button class="action-btn" id="viewWeek">SEE THIS WEEK 🏆</button>`);$('#viewWeek').onclick=()=>{closeModal();resetHome();showScreen('weekScreen')}}
function resetHome(){clearInterval(state.timer);state.timer=null;$('#preDinnerCard').classList.remove('hidden');$('#timerCard').classList.add('hidden');$('#puppy').classList.remove('celebrate')}
function renderWeek(){let d=load(),start=weekStart(),days=[],total=0,scores=[];for(let i=0;i<7;i++){let x=new Date(start);x.setDate(start.getDate()+i);let k=dateKey(x),r=d.history[k];if(r){total+=r.score;scores.push(r.score)}days.push({x,k,r})}$('#weekScore').textContent=total;$('#goalScore').textContent=d.goal||500;$('#goalFill').style.width=Math.min(100,total/(d.goal||500)*100)+'%';$('#goalMessage').textContent=total>=(d.goal||500)?'🎉 Ice cream reward unlocked! Amazing week!':'Earn ribbons at dinner to fill the sundae meter!';$('#dayGrid').innerHTML=days.map(o=>`<div class="day ${o.k===dateKey()?'today':''}"><div class="dow">${o.x.toLocaleDateString(undefined,{weekday:'short'}).toUpperCase()}</div><div class="medal">${o.r?(o.r.score>=100?'🏆':o.r.score>=75?'🥇':o.r.score>=50?'🥈':'🐾'):'○'}</div><div class="pts">${o.r?o.r.score:'—'}</div><div class="date">${o.x.toLocaleDateString(undefined,{month:'short',day:'numeric'})}</div></div>`).join('');$('#dinnersCount').textContent=scores.length;$('#bestScore').textContent=scores.length?Math.max(...scores):0;$('#avgScore').textContent=scores.length?Math.round(total/scores.length):0}
$('#settingsBtn').onclick=()=>{let d=load();modal(`<div class="settings"><h2>Parent Settings</h2><label>Weekly ice cream goal</label><input id="goalInput" type="number" min="100" max="700" step="25" value="${d.goal||500}"><p>Each dinner can earn up to 100 points. The default goal is 500.</p><button class="action-btn" id="saveSettings">SAVE</button><button class="action-btn danger" id="clearWeek">CLEAR THIS WEEK</button></div>`);$('#saveSettings').onclick=()=>{let x=load();x.goal=Math.max(100,Math.min(700,Number($('#goalInput').value)||500));save(x);closeModal();renderWeek()};$('#clearWeek').onclick=()=>{let x=load(),s=weekStart();for(let i=0;i<7;i++){let dt=new Date(s);dt.setDate(s.getDate()+i);delete x.history[dateKey(dt)]}save(x);closeModal();renderWeek()}}
function confetti(){let c=$('#confetti');for(let i=0;i<36;i++){let e=document.createElement('i');e.textContent=['⭐','🎉','🐾','🏆','💛'][Math.floor(Math.random()*5)];e.style.left=Math.random()*100+'vw';e.style.animationDelay=Math.random()*.5+'s';e.style.fontSize=14+Math.random()*18+'px';c.appendChild(e);setTimeout(()=>e.remove(),2400)}}
(function init(){let d=load();if(d.active){$('#preDinnerCard').classList.add('hidden');$('#timerCard').classList.remove('hidden');tick();state.timer=setInterval(tick,1000)}if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')})();
